### ISSUE TITLE
[vite] Internal server error: Cannot read property 'theme' of undefined

### ISSUE THREAD

**Issue by sudo-shihab** [adamwathan/tailwind-jit-vite-example#3]
Tried to run this project to check tailwind `--jit` configuration with vite but ran into a problem intially which was popping like

![vite-jit-tailwindPNG](https://user-images.githubusercontent.com/58358409/124227455-52d81600-db28-11eb-87c3-badccfb8ff1a.PNG)

Solved the above  issue by adding latest `tailwindcss`  and `postcss` package but when again tried to run this project a new error has popped up which states like this -

`[vite] Internal server error: Cannot read property 'theme'` ->

![vite-tail-jit-issue](https://user-images.githubusercontent.com/58358409/124227618-9cc0fc00-db28-11eb-8eee-9cf054c825f4.PNG)

Any resolution for the above error please , Tried deleting NM folder and lock file , Tried updating all packages ( with yarn and npm ) but nothing seems to be working as such :/

Thanks you , let me known if I need to share more info on this.

**Comment by sudo-shihab** [comment]
@adamwathan : ^^ looking forward for a fix for the above . Thanks :)

**Comment by adamwathan** [comment]
This project is really old and was a demo of the old @tailwindcss/jit library which is now deprecated since JIT is part of Tailwind itself. I cloned it, updated the dependencies and swapped over to `tailwindcss` instead of `@tailwindcss/jit` and everything seems to be working fine here, no error like what you saw above.

If you are having problems with Tailwind, the best place to report an issue is on the Tailwind repo itself. Make sure you include a reproduction (as an actual repository, screenshots are not quite enough I'm afraid) and happy to help there.

**Comment by sudo-shihab** [comment]
Thank you so much @adamwathan  , much appreciated 👍 tried the FIX as you mentioned ( updated all packages and removed jit pckg and enabled `jit` mode) , The error I reported is gone and I am able to run the project now however again another issue follows this  :/ as I guess `Vite`  ( v2.3.8 ) is giving HMR update issue , I am not sure if you are aware of it or not , enabling JIT mode via tailwind config file is not triggering any HMR update to `index.html`  file , instead if we change any content within index.html (default entry point for vite) it triggers HMR update for tailwind.css file , every single time.
